FROM jwt-nginx-s3

# Cleanup
RUN  apk del .build-deps \
  && apk del .gettext \
  && rm -rf /tmp/*

# Get nginx ready to run
COPY tmp/resources/nginx.conf /etc/nginx/nginx.conf
COPY tmp/resources/test-jwt-nginx.conf /etc/nginx/conf.d/test-jwt-nginx.conf

EXPOSE 8000

STOPSIGNAL SIGTERM

CMD ["nginx", "-g", "daemon off;"]
